#!/usr/bin/env zsh

alias randstr="cat /dev/urandom | env LC_CTYPE=C tr -cd 'A-Za-z0-9' | head -c"
alias rake='noglob rake'
alias tiga='tig --all'
alias arc='OVERCOMMIT_DISABLE=1 arc'
alias q='ag -Q'
alias .='cd .'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

alias mkvirtualenv3='mkvirtualenv --python=$(which python3)'

function cdws() {
cd $HOME/workspace/$1
}

function mkws() {
mkdir -p $HOME/workspace/$1
}

compctl -/ -W $HOME/workspace cdws
compctl -/ -W $HOME/workspace mkws

function serve() {
port="${1:-3000}"
ruby -run -e httpd . -p $port
}
